/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import escalonadores.FCFS;
import escalonadores.RR;
import escalonadores.SJF;
import gerais.LeitorArquivo;
import java.io.File;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas
 */
public class EscalonadorTela extends javax.swing.JFrame {

    private File arquivo;
    private FCFS fcfs;
    private SJF sjf;
    private RR rr;
    private ArrayList<String> listaPlot;

    /**
     * Creates new form view
     */
    public EscalonadorTela() {
        initComponents();
        jButtonStart.setEnabled(false);
        jButtonStep.setEnabled(false);
        jButtonStepBack.setEnabled(false);
        jTableGraphic.getTableHeader().setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonStart = new javax.swing.JButton();
        jComboBoxEscalonadores = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGraphic = new javax.swing.JTable();
        jButtonStep = new javax.swing.JButton();
        jButtonImportar = new javax.swing.JButton();
        jButtonStepBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButtonStart.setText("Play All");
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });

        jComboBoxEscalonadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "SJF", "RR" }));
        jComboBoxEscalonadores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEscalonadoresItemStateChanged(evt);
            }
        });

        jTableGraphic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableGraphic.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableGraphic.setEnabled(false);
        jTableGraphic.setFocusable(false);
        jTableGraphic.setGridColor(new java.awt.Color(255, 255, 255));
        jTableGraphic.setRequestFocusEnabled(false);
        jTableGraphic.setShowHorizontalLines(false);
        jTableGraphic.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTableGraphic);

        jButtonStep.setText("|>");
        jButtonStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStepActionPerformed(evt);
            }
        });

        jButtonImportar.setText("Importar");
        jButtonImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportarActionPerformed(evt);
            }
        });

        jButtonStepBack.setText("<|");
        jButtonStepBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStepBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonImportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxEscalonadores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonStepBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonStep)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxEscalonadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonImportar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonStart)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonStep)
                            .addComponent(jButtonStepBack)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed
        PlotTable.reset();
        this.executar();
        PlotTable.plotAll(jTableGraphic, listaPlot, LeitorArquivo.getQuantidadeProcessos());
        jButtonStepBack.setEnabled(true);
        jButtonStep.setEnabled(false);

    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStepActionPerformed

        this.executar();
        PlotTable.plotStep(jTableGraphic, listaPlot, LeitorArquivo.getQuantidadeProcessos());
        jButtonStepBack.setEnabled(true);
        if (PlotTable.getStep() == listaPlot.size()) {
            jButtonStep.setEnabled(false);
        }

    }//GEN-LAST:event_jButtonStepActionPerformed

    private void jButtonImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportarActionPerformed
        arquivo = LeitorArquivo.carregarArquivo();
        if (arquivo != null) {
            jButtonStart.setEnabled(true);
            jButtonStep.setEnabled(true);
        }
        PlotTable.reset();
        jTableGraphic.setModel(new DefaultTableModel());

    }//GEN-LAST:event_jButtonImportarActionPerformed

    private void jButtonStepBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStepBackActionPerformed

        PlotTable.stepBack(jTableGraphic, listaPlot, LeitorArquivo.getQuantidadeProcessos());
        if (PlotTable.getStep() == 0) {
            jButtonStepBack.setEnabled(false);
        }
        jButtonStep.setEnabled(true);


    }//GEN-LAST:event_jButtonStepBackActionPerformed

    private void jComboBoxEscalonadoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEscalonadoresItemStateChanged
        PlotTable.reset();
        jTableGraphic.setModel(new DefaultTableModel());
        jButtonStepBack.setEnabled(false);
        if (arquivo != null) {
            jButtonStep.setEnabled(true);
        }

    }//GEN-LAST:event_jComboBoxEscalonadoresItemStateChanged

    private void executar() {
        switch ((String) jComboBoxEscalonadores.getSelectedItem()) {
            case "FCFS":
                fcfs = new FCFS(LeitorArquivo.montarLista(arquivo));
                listaPlot = fcfs.executar();
                break;
            case "SJF":
                sjf = new SJF(LeitorArquivo.montarLista(arquivo));
                listaPlot = sjf.executar();
                break;
            case "RR":
                rr = new RR(LeitorArquivo.montarLista(arquivo), 2);
                listaPlot = rr.executar();
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscalonadorTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscalonadorTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscalonadorTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscalonadorTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscalonadorTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonImportar;
    private javax.swing.JButton jButtonStart;
    private javax.swing.JButton jButtonStep;
    private javax.swing.JButton jButtonStepBack;
    private javax.swing.JComboBox<String> jComboBoxEscalonadores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGraphic;
    // End of variables declaration//GEN-END:variables

}
